ignore:
  - cmake/
  - doc/
  - examples/
  - src/common/
  - src/valgrind/
  - tests/
  - utils/

comment:
  layout: "diff"
  behavior: default
  require_changes: true

parsers:
  gcov:
    branch_detection:
      conditional: no
      loop: no
      method: no
      macro: no
